version: '3.1'

volumes:
   db-data: {}

networks:
  pdb:
    driver: bridge

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passdb
      - POSTGRES_DB=db_otus
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - pdb