version: '3.1'

volumes:
  db-data: {}

networks:
  pdb:
    driver: bridge

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passdb
      - POSTGRES_DB=user_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pdb

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.ru
      - PGADMIN_DEFAULT_PASSWORD=passdb
    ports:
      - "5050:80"
    restart: always
    networks:
      - pdb